options:
  autoremove:
    default: true
    description: |
      Wether to autoremove the certificate from LXD's
      trusted list when the relation is broken.
    type: boolean
  projects:
    description: |
      Comma separated list of projects to give access to.
      If not provided, the client will have full unrestricted access
      to everything. If however the projects list is an empty list,
      the client will not have access to anything.
    type: string
