series: focal
machines:
  "0":
    # Infrastructure services
    series: focal
  "1":
    # Infrastructure services
    series: focal
  "2":
    # Compute
    series: focal
  "3":
    # Compute
    series: focal
  "4":
    # Compute
    series: focal
applications:
  prometheus2:
    charm: prometheus2
    channel: stable
    series: focal
    num_units: 1
    to:
      - 0
  grafana:
    charm: grafana
    num_units: 1
    to:
      - 1
  lxd:
    charm: lxd
    options:
      lxd-listen-https: true
      mode: cluster
    num_units: 3
    to:
    - 2
    - 3
    - 4
relations:
- - prometheus2:grafana-source
  - grafana:grafana-source
- - prometheus2:manual-jobs
  - lxd:prometheus-manual
- - lxd:grafana-dashboard
  - grafana:dashboards
