series: focal
machines:
  "0":
    # Infrastructure services
    constraints: tags=cloud
    series: focal
  "1":
    # Infrastructure services
    constraints: tags=cloud
    series: focal
  "2":
    # Compute
    constraints: tags=cloud
    series: focal
  "3":
    # Compute
    constraints: tags=cloud
    series: focal
  "4":
    # Compute
    constraints: tags=cloud
    series: focal
applications:
  prometheus2:
    charm: prometheus2
    # requires revision 28 or later hence edge and focal
    channel: edge
    series: focal
    num_units: 1
    to:
      - 0
  grafana:
    charm: grafana
    num_units: 1
    to:
      - 1
  lxd:
    charm: lxd
    options:
      lxd-listen-https: true
      snap-channel: latest/edge
      mode: cluster
    num_units: 3
    to:
    - 2
    - 3
    - 4
relations:
- - prometheus2:manual-jobs
  - lxd:prometheus-manual
- - prometheus2:grafana-source
  - grafana:grafana-source
- - lxd:grafana-dashboard
  - grafana:dashboards
