name: Builds
on:
  - push
  - pull_request

jobs:
  charm:
    name: Charm package
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
          sudo snap refresh lxd --channel=latest
          sudo adduser "$USER" lxd
          sudo lxd init --auto
          sudo snap install charmcraft --classic

    - name: Build charm
      run: |
          set -eux
          sudo -g lxd charmcraft pack

    - name: Upload charm
      uses: actions/upload-artifact@v3
      with:
        name: lxd-amd64-charm
        path: lxd_ubuntu-*-amd64.charm
